PrimozRatej/app@master:
  - android/
  - ios/
  - assets/
  - lib/
  - linux
  - macos/
  - test/
  - web/
  - windows
  - .gitignore
  - .metadata
  - analysis_options.yaml
  - l10n.yaml
  - pubspec.lock
  - pubspec.yaml
PrimozRatej/app-flavored@main:
  - android/
  - ios/
  - assets/
  - lib/
  - linux
  - macos/
  - test/
  - web/
  - windows
  - .gitignore
  - .metadata
  - analysis_options.yaml
  - l10n.yaml
  - pubspec.lock
  - pubspec.yaml