name: flavored

on:
  push:
    tags:
      - "v*"

jobs:
  create_version_number:
    strategy:
      matrix:
        target: [opener, humhubCommunity, somedemoproject12345]
    permissions:
      contents: write
    uses: PrimozRatej/app/.github/workflows/create-version-number.yml@f-flavored-sdp-forked
    with:
      flavor: ${{ matrix.target }}

  build_android:
    needs: [create_version_number]
    strategy:
      matrix:
        target: [ opener, humhubCommunity, somedemoproject12345 ]
    permissions:
      contents: write
    uses: PrimozRatej/app/.github/workflows/build-android.yml@f-flavored-sdp-forked
    with:
      flavor: ${{ matrix.target }}
