name: flavored

on:
  push:
    tags:
      - "v*"

jobs:
  flavor_release:
    strategy:
      matrix:
        target: [opener, humhubCommunity, somedemoproject12345]
    name: Flavor Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Trigger version-release workflow
        run: ./.github/workflows/version-release.yml  # Run the workflow after fetching the repository
        with:
          target: ${{ matrix.target }}
