name: flavored

on:
  push:
    tags:
      - "v*"

jobs:
  flavor_release:
    strategy:
      matrix:
        target: [opener, humhubCommunity, somedemoproject12345]
    name: Flavor Release
    runs-on: ubuntu-latest
    steps:
      - name: Trigger version-release workflow
        uses: .github/workflows/version-release.yml
        with:
          target: ${{ matrix.target }}
