name: flavored

on:
  push:
    tags:
      - "v*"

jobs:
  flavor_release:
    strategy:
      matrix:
        target: [opener, humhubCommunity, somedemoproject12345]
    uses: PrimozRatej/app/.github/workflows/deployment.yml@f-flavored-sdp-forked
    with:
      target: ${{ matrix.target }}
