name: Sync Repo1 to Repo2

on:
  push:
    branches:
      - '*'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from Repo1
        uses: actions/checkout@v2
        with:
          repository: PrimozRatej/app-flavored
          fetch-depth: 0
          token: ${{ secrets.REPO2_TOKEN }}

      - name: Filter files
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git clone --mirror https://github.com/PrimozRatej/app.git filtered-repo
          # Filter out files/folders you want to exclude
          # For example:
          # git filter-repo --invert-paths --path README.md --path .github
          EXCLUDE=("README.md" ".github")
          for item in "${EXCLUDE[@]}"; do
              git rm -r --cached "$item"
          done
          git commit -m "Exclude specified files/folders" --allow-empty

      - name: Push changes to repo2
        run: |
          git remote set-url origin https://github.com/PrimozRatej/app-flavored.git
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git push origin main
