name: Sync Repo1 to Repo2

on:
  push:
    branches:
      - master  # Adjust the branch name as needed

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Filter files
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@github.com"
          git clone --mirror https://github.com/PrimozRatej/app.git filtered-repo
          # Filter out files/folders you want to exclude
          # For example:
          # git filter-repo --invert-paths --path README.md --path .github
          EXCLUDE=("README.md" ".github")
          for item in "${EXCLUDE[@]}"; do
              git rm -r --cached "$item"
          done
          # Set up authentication for repo2 using PAT
          git remote set-url origin https://github.com/PrimozRatej/app-flavored.git
          git config --global credential.helper store
          echo "https://github.com/PrimozRatej:$(echo $REPO2_TOKEN)" > ~/.git-credentials
          git push origin main
