name: Sync Repo1 with Repo2

on:
  push:
    branches:
      - '*'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo1
        uses: actions/checkout@v2
        with:
          repository: PrimozRatej/app
          ref: master
          path: repo1

      - name: Checkout Repo2
        uses: actions/checkout@v2
        with:
          repository: PrimozRatej/app-flavored
          ref: main
          path: repo2
          token: ${{ secrets.REPO2_TOKEN }}  # Using again
        env:
          token: ${{ secrets.REPO2_TOKEN }}  # Using again

      - name: Copy Files to Repo2
        run: |
          # Copy all folders and files from repo1 to repo2
          rsync -av --exclude='.git' --exclude='.github' ./repo1/ ./repo2/

      - name: Commit and Push to Repo2
        run: |
          cd ./repo2
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "Sync from repo1"
          git push origin main || { 
            git checkout -b feature-branch-$GITHUB_RUN_NUMBER
            git commit -m "Conflicting changes - resolve manually"
            git push -u origin feature-branch-$GITHUB_RUN_NUMBER
          }
        env:
          token: ${{ secrets.REPO2_TOKEN }}  # Using the secret as an environment variable
